## Задание на практическую работу №13
· Создать метод, бросающий исключение типа Exception, поймать его при помощи try catch.

· Создать собственный тип исключения, бросать его из другого метода, использовать один блок try catch для обработки обоих исключений.

· Использовать блок finally для выполнения важных действий.

· Создать свой тип исключения, унаследовав его от RuntimeException, проверить, что выбрасывание такого сключения не обязывает программиста использовать try catch или обновлять сигнатуру вызывающего метода.